name: i69n
description: Simple internationalization tool for Dart and Flutter, based on
  YAML files and source code generation.
version: 3.4.0
homepage: https://github.com/fnx-io/i69n

environment:
  sdk: ^3.6.0

dependencies:
  build: ">=2.4.2 <5.0.0"
  build_config: ^1.1.2
  code_builder: ^4.11.0
  collection: ^1.19.1
  dart_style: ^3.0.0
  equatable: ^2.0.7
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  coverage: ^1.15.0
  lints: ^5.0.0
  test: ^1.25.15
